---
title: "Homework 1: Working with Vectors"
author: 
- Author1
date: "`r Sys.time()`"
output: html_notebook
---

```{r setup, include=FALSE}
# Install packages if necessary

```

## Setup
Define the following vectors, which represent the square footage and price of homes in Syracuse, NY. 

```
sqft <- c(1798,1554,1778,1500,1362,1468,1264)
selling_price <- c(189900,125000,179900,134900,164900,138900,169900)

# Define a variable:
a <- 150900
```
You'll need to copy/paste the code above into a code chunck below
```{r}

# Insert code above into this chunk. Everything included in this code chunk is interpreted by R. Code excluded from the chunk is just text that R/RStudio cannot "see."

```




Now that you have some data – explore

## Step 1: Calculating means

```{r}

#1) Compute, using R, the average square footage of homes (called mean in R)

#2) Compute, using R, the average selling price of homes  (called mean in R)

#3) Calculate the length of the vector ‘sqft’ and ‘selling_price’

#4) Calculate the sum of square footage

#5) Compute the average of both square footage and selling price, by dividing the sum (of the square footage or the selling price, as appropriate), by the length of the vector. How does this compare to the ‘mean’ function?


```

## Step 2: Using max/min functions
```{r}

#6) Compute the max square footage, store the result in ‘max_sqft’

#7) Compute the min selling price, store the results in ‘min_price’

```

## Step 3: Vector Math
```{r}

#8) Create a new vector, which is the square footage + 500 (every home had a 500 square foot addition)

#9) Compute the selling price/square footage for each home, using the new square footage just created above

```


## Step 4: Using Conditional if statements

Hint: In R, one can do:
```
if ( 100 < 150 ) "100 is less than 150" else "100 is greater than 150"
```

```{r}

#10) Write the R code to test if max max_sqft is greater than 2000 (output "yes" or "no"")

#11) Write the R code to if min min_price is greater than the variable ‘a’ (output "yes" or "no")

```


